[workspace]
changelog_path="./CHANGELOG.md"
dependencies_update = false
publish_timeout = "30m"
git_release_enable = false
git_tag_enable = false

[changelog]
commit_parsers = [
    # dont include chore changes in changelog
    { message = "^chore.*", skip = true },
    { message = "^test.*", skip = true },
    { message = "^docs.*", skip = true },
    { message = "^feat", group = "added" },
    { message = "^changed", group = "changed" },
    { message = "^deprecated", group = "deprecated" },
    { message = "^fix", group = "fixed" },
    { message = "^security", group = "security" },
    { message = "^.*", group = "other" },
]
body = """
## [{{ version | trim_start_matches(pat="v") }}]\
    {%- if release_link -%}\
        ({{ release_link }})\
    {% endif %} \
    - {{ timestamp | date(format="%Y-%m-%d") }}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}

    {% for commit in commits %}
        {%- if commit.scope -%}
            - *({{commit.scope}})* {% if commit.breaking %}[**breaking**] {% endif %}\
                {{ commit.message }}{{ self::username(commit=commit) }}\
                {%- if commit.links %} \
                    ({% for link in commit.links %}[{{link.text}}]({{link.href}}) {% endfor -%})\
                {% endif %}
        {% else -%}
            - {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message }}{{ self::username(commit=commit) }}{{ self::pr(commit=commit) }}
        {% endif -%}
    {% endfor -%}
{% endfor %}
{%- if remote.contributors %}
### Contributors
{% for contributor in remote.contributors %}
    * @{{ contributor.username }}
{%- endfor %}
{% endif -%}
{%- macro username(commit) -%}
    {% if commit.remote.username %} (by @{{ commit.remote.username }}){% endif -%}
{% endmacro -%}
{%- macro pr(commit) -%}
    {% if commit.remote.pr_number %} - #{{ commit.remote.pr_number }}{% endif -%}
{% endmacro -%}
"""

[[package]]
name = "bevy_mod_scripting"
publish_features = ["lua54"]
version_group = "main"
git_release_latest = true
git_release_enable = true
git_tag_enable = true
git_tag_name = "v{{ version }}"
git_release_name = "v{{ version }}"

[[package]]
name = "bevy_mod_scripting_lua"
publish_features = ["lua54"]
version_group = "main"

[[package]]
name = "bevy_mod_scripting_core"
version_group = "main"

[[package]]
name = "bevy_mod_scripting_derive"
version_group = "main"

[[package]]
name = "bevy_mod_scripting_rhai"
version_group = "main"

# [[package]]
# name = "bevy_mod_scripting_rune"
# version_group = "main"

[[package]]
name = "bevy_mod_scripting_functions"
version_group = "main"

[[package]]
name = "ladfile"
git_release_enable = true
git_release_latest = false
git_tag_enable = true
git_tag_name = "v{{ version }}-ladfile"
git_release_name = "v{{ version }}-ladfile"

[[package]]
name = "ladfile_builder"
git_release_enable = true
git_release_latest = false
git_tag_enable = true
git_tag_name = "v{{ version }}-ladfile_builder"
git_release_name = "v{{ version }}-ladfile_builder"

[[package]]
name = "mdbook_lad_preprocessor"
git_release_enable = true
git_release_latest = false
git_tag_enable = true
git_tag_name = "v{{ version }}-mdbook_lad_preprocessor"
git_release_name = "v{{ version }}-mdbook_lad_preprocessor"
